//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemChecker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class FloatProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static FloatProperties defaultInstance = ((FloatProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FloatProperties())));
        
        public static FloatProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.001")]
        public decimal maxFloatValue_FN {
            get {
                return ((decimal)(this["maxFloatValue_FN"]));
            }
            set {
                this["maxFloatValue_FN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.080")]
        public decimal maxFloatValue_MW {
            get {
                return ((decimal)(this["maxFloatValue_MW"]));
            }
            set {
                this["maxFloatValue_MW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.175")]
        public decimal maxFloatValue_FT {
            get {
                return ((decimal)(this["maxFloatValue_FT"]));
            }
            set {
                this["maxFloatValue_FT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.400")]
        public decimal maxFloatValue_WW {
            get {
                return ((decimal)(this["maxFloatValue_WW"]));
            }
            set {
                this["maxFloatValue_WW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.500")]
        public decimal maxFloatValue_BS {
            get {
                return ((decimal)(this["maxFloatValue_BS"]));
            }
            set {
                this["maxFloatValue_BS"] = value;
            }
        }
    }
}
