//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemChecker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class SettingsProperties : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsProperties defaultInstance = ((SettingsProperties)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsProperties())));
        
        public static SettingsProperties Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrencyApiKey {
            get {
                return ((string)(this["CurrencyApiKey"]));
            }
            set {
                this["CurrencyApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Currency {
            get {
                return ((int)(this["Currency"]));
            }
            set {
                this["Currency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("72")]
        public decimal CurrencyValue {
            get {
                return ((decimal)(this["CurrencyValue"]));
            }
            set {
                this["CurrencyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Quit {
            get {
                return ((bool)(this["Quit"]));
            }
            set {
                this["Quit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetHours {
            get {
                return ((bool)(this["SetHours"]));
            }
            set {
                this["SetHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/0001 17:30:00")]
        public global::System.DateTime TurnOn {
            get {
                return ((global::System.DateTime)(this["TurnOn"]));
            }
            set {
                this["TurnOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/0001 07:30:00")]
        public global::System.DateTime TurnOff {
            get {
                return ((global::System.DateTime)(this["TurnOff"]));
            }
            set {
                this["TurnOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotEnoughBalance {
            get {
                return ((bool)(this["NotEnoughBalance"]));
            }
            set {
                this["NotEnoughBalance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CancelOrder {
            get {
                return ((int)(this["CancelOrder"]));
            }
            set {
                this["CancelOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Net.CookieContainer SteamCookies {
            get {
                return ((global::System.Net.CookieContainer)(this["SteamCookies"]));
            }
            set {
                this["SteamCookies"] = value;
            }
        }
    }
}
